module.exports.productDB = require('./productDB')
module.exports.orderDB = require('./orderDB')
module.exports.userDB = require('./userDB')
module.exports.tokenDB = require('./tokenDB')
module.exports.purchaseDB = require('./purchaseDB')
